### PR TITLE
Added support for native stream resolution

### PR DESCRIPTION
**Pull request by bakedChicken**
Added support for native stream resolution. More information about result could be found in this issue: https://github.com/moonlight-stream/moonlight-ios/issues/442

Of course this is not for every game, but I found that Civilization 6 supports this resolution well.

### CODE REVIEW

**Comment by cgutman** [comment]
I'd like the native resolution to appear in the button label, so users don't have to go look up what their device's native resolution is. Can you implement that?

**Comment by bakedChicken** [comment]
You mean to show it just as an additional information in settings or actually extract this option out of segments and implementing this as a button with actual resolution as a button label?

**Comment by cgutman** [comment]
I think it would be nice for the button itself to have the actual resolution. You can either insert the segment at runtime, or just change the title at runtime.

**Comment by bakedChicken** [comment]
I have added a label with chosen resolution information. It looks like this:

7C452E0A-7440-4787-96B7-6DA181BB5F85_1_105_c

**Comment by cgutman** [comment]
Hmm, what I had in mind was the segment button itself displaying the native resolution. But at the very least, we need to get the segment sizing correct so the text isn't cut off.

**Comment by nkulung** [comment]
A resolution option (either native or somewhere between 1080P and 4K) would be great to have available. Is there a dropdown element that could be used in place of the segments? 

I think a 2K resolution would be perfect, A 4:3 aspect ratio resolution would be great as well, but I figure that it doesn't scale that well with certain applications/games.

**Comment by cgutman** [comment]
Superseded by #476

**Pull request closed without merging**
