### PR TITLE
tvOS Support

### PR DESCRIPTION
**Pull request by apocolipse**
This PR adds in hackish tvOS support, based on the work by @kevsmithpublic from https://github.com/kevsmithpublic/moonlight-ios
His fork was outdated and no longer connected to latest GE, as well it was to far gone to merge, finally it was geared towards just tvOS and not shared code between iOS and tvOS.

Notes:
- Requires modifying SDK headers to remove `__TVOS_PROHIBITED`
- Shared codebase, precompiler directives used to share code between iOS and tvOS
- Added a tvOS specific target to `moonlight-common` since static libs have to have specific targets (Future work should move this to a shared framework if possible)
- Settings page now available ("click" on the "Moonlight" button, swipe unavailable.  Menu to exit settings page)
- Buttons added in lieu of slider to adjust bitrate settings

### CODE REVIEW

**Comment by bassrock** [comment]
Is there a rdar that we can duplicate?

**Comment by apocolipse** [comment]
http://www.openradar.me/25661358

**Comment by ajmi982** [comment]
Great. Fingers crossed they get this resolved in the next beta.

**Comment by mrb113** [comment]
We can't pull this in to Moonlight since we can't ship anything that modifies the SDK. I'm closing the pull request but feel free to make your instructions available to those who want to build it themselves and run it on apple tv.
 We're hoping to hear more about the Apple TV API availability, too.

**Comment by apocolipse** [comment]
@mrb113 Understandable.  To be fair, it can be merged with no ill effect to the rest of the codebase, one just can't build nor deploy to the tvOS AppStore without the SDK Modifications.  
I would also strongly recommend merging as to prevent further conflicts as you continue working on the main codebase as this PR was simply reworking someone else's work to reconcile conflicts that had arisen since he wrote it, so it will likely require some extra work to get it in once the required API is made available or a working alternative is found.
On a related note, I spoke with several Apple engineers at WWDC asking about the API's availability and got the runaround, nobody knew why its not available nor is that Radar actively being looked at.  

I'll dig around some more and see if I can find an alternative approach that uses available API's, if I'm successful I'll re-open.

**Comment by bassrock** [comment]
I would concur with @apocolipse keeping the code merged in won't affect the rest of the codebase and will allow those of us with dev ability to continue building it. I'm also curious if anyone has tried building it against the tvOS 10 SDK and submitting it to TestFlight. It's possible that TestFlight may not detect it on their end if the docs say it is available.

**Comment by apocolipse** [comment]
@bassrock Submitting to Testflight goes through the same process as submitting to the AppStore.  It runs an API usage scan to check for unavailable API's and would be blocked from being uploaded just the same.  As for Xcode 10, one can't submit to Testflight with it yet anyway, and the API is still marked unavailable.

**Comment by bassrock** [comment]
Hmm ok. I thought they updated Testflight already with iOS 10 support.

**Comment by cgutman** [comment]
I'd be open to merging this if you cleanup the iOS/tvOS separation some. I'd to unify the code paths to try to avoid tvOS-specific stuff as much as possible.

**Comment by apocolipse** [comment]
@cgutman Sure thing, what/how would you like things cleaned up?  The only files that are tvOS exclusive are assets (storyboard+images), The rest otherwise is integrated into the same code splitting tvOS specific stuff off w/ directives
```objc
#if TARGET_OS_IOS
...
 #elif TARGET_OS_TV
...
 #endif
```
This occurs frequently however but the key things to note that must be changed for tvOS are Caches not Documents directory, no UIFont stuff, no normal UIAction stuff, disabled swipe gestures (they work oddly enough but not as intended), and device default settings.

**Comment by jeregrine** [comment]
FYI in the latest Xcode those API's are no longer prohibited 

AVF_EXPORT NSString *const AVSampleBufferDisplayLayerFailedToDecodeNotification API_AVAILABLE(macos(10.10), ios(8.0), tvos(10.2)) __WATCHOS_PROHIBITED; // decode failed, see NSError in notification payload
AVF_EXPORT NSString *const AVSampleBufferDisplayLayerFailedToDecodeNotificationErrorKey API_AVAILABLE(macos(10.10), ios(8.0), tvos(10.2)) __WATCHOS_PROHIBITED; // NSError


The merge is simple if you add a `.gitattributes` file with the line `*.pbxproj merge=union`. 

There are new xcode/swift/obj errors that are a little past my skill level. BUT Theoretically this should be possible to ship to AppleTV and the App Store.

**Comment by enigmacarpc** [comment]
@jeregrine Thanks for the update I hope someone can get this as an app store app so we dont have to deal with the revoking.

**Comment by cgutman** [comment]
We are working on tvOS support in the tvOS branch.

**Pull request closed without merging**
